export const courses = [
  {
    id: 'c1',
    title: 'Meta Front-End Developer Professional Certificate',
    provider: 'Coursera (Meta)',
    roleKeywords: ['frontend', 'front-end', 'react', 'web developer', 'javascript'],
    price: 'Paid',
    durationHours: 120,
    durationText: '7 Months',
    hasCertification: true,
    demandScore: 98,
    url: 'https://www.coursera.org/professional-certificates/meta-front-end-developer',
    image: 'https://upload.wikimedia.org/wikipedia/commons/a/ab/Meta-Logo.png'
  },
  {
    id: 'c2',
    title: 'CS50: Introduction to Computer Science',
    provider: 'edX (Harvard)',
    roleKeywords: ['computer science', 'software engineer', 'backend', 'developer', 'c', 'python'],
    price: 'Free',
    durationHours: 144,
    durationText: '12 Weeks',
    hasCertification: true,
    demandScore: 95,
    url: 'https://www.edx.org/cs50',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Harvard_University_logo.svg/512px-Harvard_University_logo.svg.png'
  },
  {
    id: 'c3',
    title: 'JavaScript Data Structures and Algorithms',
    provider: 'freeCodeCamp',
    roleKeywords: ['frontend', 'javascript', 'software engineer', 'web developer'],
    price: 'Free',
    durationHours: 300,
    durationText: '300 Hours',
    hasCertification: true,
    demandScore: 88,
    url: 'https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/',
    image: 'https://upload.wikimedia.org/wikipedia/commons/3/39/FreeCodeCamp_logo.png'
  },
  {
    id: 'c4',
    title: 'React - The Complete Guide (incl Hooks, React Router, Redux)',
    provider: 'Udemy',
    roleKeywords: ['frontend', 'react', 'javascript', 'web developer'],
    price: 'Paid',
    durationHours: 50,
    durationText: '50 Hours',
    hasCertification: true,
    demandScore: 92,
    url: 'https://www.udemy.com/course/react-the-complete-guide-incl-redux/',
    image: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Udemy_logo.svg'
  },
  {
    id: 'c5',
    title: 'Google Data Analytics Professional Certificate',
    provider: 'Coursera (Google)',
    roleKeywords: ['data analyst', 'data science', 'sql', 'r'],
    price: 'Paid',
    durationHours: 180,
    durationText: '6 Months',
    hasCertification: true,
    demandScore: 99,
    url: 'https://www.coursera.org/professional-certificates/google-data-analytics',
    image: 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg'
  },
  {
    id: 'c6',
    title: 'Machine Learning Specialization',
    provider: 'Coursera (Stanford)',
    roleKeywords: ['machine learning', 'ai', 'data science', 'python'],
    price: 'Paid',
    durationHours: 80,
    durationText: '2 Months',
    hasCertification: true,
    demandScore: 97,
    url: 'https://www.coursera.org/specializations/machine-learning-introduction',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Seal_of_Leland_Stanford_Junior_University.svg/512px-Seal_of_Leland_Stanford_Junior_University.svg.png'
  },
  {
    id: 'c7',
    title: 'Crash Course on Python',
    provider: 'Coursera (Google)',
    roleKeywords: ['python', 'software engineer', 'backend', 'data science'],
    price: 'Free',
    durationHours: 32,
    durationText: '32 Hours',
    hasCertification: false,
    demandScore: 85,
    url: 'https://www.coursera.org/learn/python-crash-course',
    image: 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg'
  },
  {
    id: 'c8',
    title: 'UI / UX Design Specialization',
    provider: 'Coursera (CalArts)',
    roleKeywords: ['ui/ux', 'ui designer', 'ux designer', 'product designer'],
    price: 'Paid',
    durationHours: 64,
    durationText: '4 Months',
    hasCertification: true,
    demandScore: 90,
    url: 'https://www.coursera.org/specializations/ui-ux-design',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Coursera_Logo_600x600.svg/512px-Coursera_Logo_600x600.svg.png'
  },
  {
    id: 'c9',
    title: 'Figma UI UX Design Essentials',
    provider: 'Udemy',
    roleKeywords: ['ui/ux', 'figma', 'ui designer', 'ux designer'],
    price: 'Paid',
    durationHours: 12,
    durationText: '12 Hours',
    hasCertification: true,
    demandScore: 94,
    url: 'https://www.udemy.com/course/figma-ui-ux-design-user-experience-tutorial/',
    image: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Udemy_logo.svg'
  },
  {
    id: 'c10',
    title: 'Learn HTML & CSS Basics',
    provider: 'Codecademy',
    roleKeywords: ['frontend', 'html', 'css', 'web developer'],
    price: 'Free',
    durationHours: 8,
    durationText: '8 Hours',
    hasCertification: false,
    demandScore: 75,
    url: 'https://www.codecademy.com/learn/learn-html',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Codecademy.svg/512px-Codecademy.svg.png'
  },
  {
    id: 'c11',
    title: 'AWS Certified Solutions Architect - Associate',
    provider: 'A Cloud Guru',
    roleKeywords: ['aws', 'cloud engineer', 'devops', 'backend'],
    price: 'Paid',
    durationHours: 40,
    durationText: '40 Hours',
    hasCertification: true,
    demandScore: 96,
    url: 'https://aws.amazon.com/certification/certified-solutions-architect-associate/',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Amazon_Web_Services_Logo.svg/512px-Amazon_Web_Services_Logo.svg.png'
  },
  {
    id: 'c12',
    title: 'Docker for the Absolute Beginner',
    provider: 'Udemy',
    roleKeywords: ['devops', 'docker', 'cloud engineer', 'backend'],
    price: 'Paid',
    durationHours: 4,
    durationText: '4 Hours',
    hasCertification: true,
    demandScore: 89,
    url: 'https://www.udemy.com/course/learn-docker/',
    image: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Udemy_logo.svg'
  }
];
